[package]
name = "spl-token"
version = "0.1.0"
edition = "2024"


[dependencies]
solana-client = "1.18.11"
solana-sdk = "1.18.11"
spl-token = "4.0.0"
mpl-token-metadata = "4.1.2"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
spl-associated-token-account = "2.3.0"
spl-token-metadata-interface = "1.0.0"
serde_json = "1.0.149"
