[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
assignment_4 = "AeQkytk9pprRY2AfZgaaJiisH2ZAiu7Mp5Dg75ieacNR"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
