[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
assignment_4 = "8VwFfb5WFfgaJVUSPtUC7W2QKYWUwBQyk7VBiYNVBv1E"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
