[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_program = "Ebvs4JtK8PS82ZR981QRTvRLdn3fX5iWBm9sRJ3NUjBv"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
